packages:
  - 'packages/*'

# Catalog for shared dependencies
catalog:
  # Core dependencies
  typescript: ^5.6.3
  zod: ^3.23.8

  # Anthropic AI
  '@anthropic-ai/sdk': ^0.32.1

  # LangChain (for agent-graph V2)
  # Note: @langchain/core is overridden to ~1.1.4 in package.json to resolve
  # peer dependency conflicts. The tilde (~) is stricter than the caret (^)
  # used here - it allows patches (1.1.5, 1.1.6) but not minor updates (1.2.0).
  # This prevents multiple @langchain/core versions while allowing security fixes.
  '@langchain/anthropic': ^0.3.9
  '@langchain/core': ^1.1.2
  '@langchain/langgraph': ^0.2.19
  langchain: ^1.1.3

  # Build tools
  tsx: ^4.19.2
  vite: ^5.4.11

  # Testing
  vitest: ^2.1.8

  # Node types
  '@types/node': ^22.9.0

# Note: Settings like shared-workspace-lockfile, auto-install-peers, and
# strict-peer-dependencies are configured in .npmrc to avoid duplication
