packages:
  - 'packages/*'

# Catalog for shared dependencies
catalog:
  # Core dependencies
  typescript: ^5.6.3
  zod: ^3.23.8

  # Anthropic AI
  '@anthropic-ai/sdk': ^0.32.1

  # LangChain (for agent-graph V2)
  '@langchain/anthropic': ^0.3.9
  '@langchain/core': ^1.1.2
  '@langchain/langgraph': ^0.2.19
  langchain: ^1.1.3

  # Build tools
  tsx: ^4.19.2
  vite: ^5.4.11

  # Testing
  vitest: ^2.1.8

  # Node types
  '@types/node': ^22.9.0

# Settings
settings:
  # Use shared node_modules at root
  shared-workspace-lockfile: true

  # Auto install peers
  auto-install-peers: true

  # Strict peer dependencies
  strict-peer-dependencies: false
